apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-index-htlm-configmap
  namespace: default
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    Version: 1.0.3
    </br>
    <h1>Hi! I got deployed in {{ .Values.env.name }} Environment using Helm Chart </h1>
    </html>