apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-service
spec:
  selector:
    app.kubernetes.io/instance: {{.Release.Name}}
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.port}}
      protocol: {{.Values.service.prototol | default "TCP"}}
      targetPort: {{.Values.service.targetPort}}
